[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.24'
# evm_version = "cancun"
optimizer_runs = 200
ffi = false
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@uniswap/v3-periphery/contracts=lib/v3-periphery/contracts',
    '@uniswap/v3-core/contracts=lib/v3-core/contracts',
    '@aave/v3-core/contracts=lib/aave-v3-core/contracts',
    '@aave/v3-periphery/contracts=lib/aave-v3-periphery/contracts',
    '@comet/contracts=lib/comet/contracts',
]


[rpc_endpoints]
polygon = "https://polygon-mainnet.g.alchemy.com/v2/<ALCHEMY_API_KEY>"
ethereum = "https://eth-mainnet.g.alchemy.com/v2/<ALCHEMY_API_KEY>"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
